### ISSUE TITLE
I have an issue with this issue tracker

### ISSUE THREAD

**Issue by teempai** [vanilladefi/issue-tracker#1]
What is the purpose of this issue tracker and how do I use it?

**Comment by JaniAnttonen** [comment]
You’re off to a good start. When you have an issue with the Vanilla dapp, which is hosted at https://vanilladefi.com you can post an issue here. Please describe the issue with as much detail as you can so that we can fix it or help you work around it.

I'm going to draft a readme to serve as a guide :)

**Comment by teempai** [comment]
Thanks. That helped. lol.
